In [35]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [36]:
df = pd.read_csv(r"D:\AI-ML Projects\Sales-Prediction\dataset\sales.csv")
df.head()

,Date,Product_Category,Price,Discount,Customer_Segment,Marketing_Spend,Units_Sold
0,01-01-2023,Sports,932.80,35.82,Occasional,6780.38,32
1,02-01-2023,Toys,569.48,3.60,Premium,6807.56,16
2,03-01-2023,Home Decor,699.68,3.56,Premium,3793.91,27
3,04-01-2023,Toys,923.27,0.61,Premium,9422.75,29
4,05-01-2023,Toys,710.17,47.83,Premium,1756.83,17

In [37]:
df.shape

(1000, 7)

In [38]:
df.columns

Index(['Date', 'Product_Category', 'Price', 'Discount', 'Customer_Segment',
       'Marketing_Spend', 'Units_Sold'],
      dtype='object')

In [39]:
df.dtypes

Date                 object
Product_Category     object
Price               float64
Discount            float64
Customer_Segment     object
Marketing_Spend     float64
Units_Sold            int64
dtype: object

In [40]:
df.head()

,Date,Product_Category,Price,Discount,Customer_Segment,Marketing_Spend,Units_Sold
0,01-01-2023,Sports,932.80,35.82,Occasional,6780.38,32
1,02-01-2023,Toys,569.48,3.60,Premium,6807.56,16
2,03-01-2023,Home Decor,699.68,3.56,Premium,3793.91,27
3,04-01-2023,Toys,923.27,0.61,Premium,9422.75,29
4,05-01-2023,Toys,710.17,47.83,Premium,1756.83,17

In [41]:
# df["Date"]= pd.to_datetime(df["Date"])
#

In [42]:
df.isnull().sum()

Date                0
Product_Category    0
Price               0
Discount            0
Customer_Segment    0
Marketing_Spend     0
Units_Sold          0
dtype: int64

In [43]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [44]:
df["Product_Category"].value_counts()

Product_Category
Electronics    210
Sports         206
Toys           204
Home Decor     190
Fashion        190
Name: count, dtype: int64

In [45]:
df["Customer_Segment"].value_counts()

Customer_Segment
Regular       345
Occasional    339
Premium       316
Name: count, dtype: int64

In [46]:
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

In [47]:
df

,Date,Product_Category,Price,Discount,Customer_Segment,Marketing_Spend,Units_Sold
0,2023-01-01,Sports,932.80,35.82,Occasional,6780.38,32
1,2023-02-01,Toys,569.48,3.60,Premium,6807.56,16
2,2023-03-01,Home Decor,699.68,3.56,Premium,3793.91,27
3,2023-04-01,Toys,923.27,0.61,Premium,9422.75,29
4,2023-05-01,Toys,710.17,47.83,Premium,1756.83,17
...,...,...,...,...,...,...,...
995,NaT,Fashion,740.06,49.06,Regular,1890.83,34
996,NaT,Electronics,517.10,28.48,Premium,8011.66,21
997,NaT,Electronics,683.43,12.98,Occasional,3408.51,19
998,NaT,Sports,51.26,21.85,Occasional,7335.62,26
999,NaT,Home Decor,93.94,29.68,Regular,4258.11,39

In [48]:
df.isna().sum()

Date                604
Product_Category      0
Price                 0
Discount              0
Customer_Segment      0
Marketing_Spend       0
Units_Sold            0
dtype: int64

In [49]:
df["Date"] = df["Date"].fillna(pd.Timestamp("2023-01-01"))

In [50]:
df

,Date,Product_Category,Price,Discount,Customer_Segment,Marketing_Spend,Units_Sold
0,2023-01-01,Sports,932.80,35.82,Occasional,6780.38,32
1,2023-02-01,Toys,569.48,3.60,Premium,6807.56,16
2,2023-03-01,Home Decor,699.68,3.56,Premium,3793.91,27
3,2023-04-01,Toys,923.27,0.61,Premium,9422.75,29
4,2023-05-01,Toys,710.17,47.83,Premium,1756.83,17
...,...,...,...,...,...,...,...
995,2023-01-01,Fashion,740.06,49.06,Regular,1890.83,34
996,2023-01-01,Electronics,517.10,28.48,Premium,8011.66,21
997,2023-01-01,Electronics,683.43,12.98,Occasional,3408.51,19
998,2023-01-01,Sports,51.26,21.85,Occasional,7335.62,26
999,2023-01-01,Home Decor,93.94,29.68,Regular,4258.11,39

In [51]:
df["Month"]= df["Date"].dt.month
df["Day"]= df["Date"].dt.day

In [52]:
df

,Date,Product_Category,Price,Discount,Customer_Segment,Marketing_Spend,Units_Sold,Month,Day
0,2023-01-01,Sports,932.80,35.82,Occasional,6780.38,32,1,1
1,2023-02-01,Toys,569.48,3.60,Premium,6807.56,16,2,1
2,2023-03-01,Home Decor,699.68,3.56,Premium,3793.91,27,3,1
3,2023-04-01,Toys,923.27,0.61,Premium,9422.75,29,4,1
4,2023-05-01,Toys,710.17,47.83,Premium,1756.83,17,5,1
...,...,...,...,...,...,...,...,...,...
995,2023-01-01,Fashion,740.06,49.06,Regular,1890.83,34,1,1
996,2023-01-01,Electronics,517.10,28.48,Premium,8011.66,21,1,1
997,2023-01-01,Electronics,683.43,12.98,Occasional,3408.51,19,1,1
998,2023-01-01,Sports,51.26,21.85,Occasional,7335.62,26,1,1
999,2023-01-01,Home Decor,93.94,29.68,Regular,4258.11,39,1,1

In [53]:
df.drop("Date", axis=1, inplace=True)

In [54]:
df

,Product_Category,Price,Discount,Customer_Segment,Marketing_Spend,Units_Sold,Month,Day
0,Sports,932.80,35.82,Occasional,6780.38,32,1,1
1,Toys,569.48,3.60,Premium,6807.56,16,2,1
2,Home Decor,699.68,3.56,Premium,3793.91,27,3,1
3,Toys,923.27,0.61,Premium,9422.75,29,4,1
4,Toys,710.17,47.83,Premium,1756.83,17,5,1
...,...,...,...,...,...,...,...,...
995,Fashion,740.06,49.06,Regular,1890.83,34,1,1
996,Electronics,517.10,28.48,Premium,8011.66,21,1,1
997,Electronics,683.43,12.98,Occasional,3408.51,19,1,1
998,Sports,51.26,21.85,Occasional,7335.62,26,1,1
999,Home Decor,93.94,29.68,Regular,4258.11,39,1,1

In [ ]:
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import OneHotEncoder

from sklearn.compose import ColumnTransformer 

from sklearn.pipeline import Pipeline

from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import r2_score, accuracy_score

In [56]:
X = df.drop("Units_Sold", axis=1)
y = df["Units_Sold"]

In [57]:
X

,Product_Category,Price,Discount,Customer_Segment,Marketing_Spend,Month,Day
0,Sports,932.80,35.82,Occasional,6780.38,1,1
1,Toys,569.48,3.60,Premium,6807.56,2,1
2,Home Decor,699.68,3.56,Premium,3793.91,3,1
3,Toys,923.27,0.61,Premium,9422.75,4,1
4,Toys,710.17,47.83,Premium,1756.83,5,1
...,...,...,...,...,...,...,...
995,Fashion,740.06,49.06,Regular,1890.83,1,1
996,Electronics,517.10,28.48,Premium,8011.66,1,1
997,Electronics,683.43,12.98,Occasional,3408.51,1,1
998,Sports,51.26,21.85,Occasional,7335.62,1,1
999,Home Decor,93.94,29.68,Regular,4258.11,1,1

In [65]:
X = df.drop("Units_Sold", axis=1)
y = df["Units_Sold"]

# Train-test split (keep as DataFrame)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Categorical columns
cat_cols = ["Product_Category", "Customer_Segment"]

# Preprocessor
preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(), cat_cols)
    ],
    remainder="passthrough"
)

# Pipeline
model = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", RandomForestRegressor())
])

# Train
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat', OneHotEncoder(),
                                                  ['Product_Category',
                                                   'Customer_Segment'])])),
                ('regressor', RandomForestRegressor())])

In [66]:
pred=model.predict(X_test)

In [67]:
pred

array([27.73, 30.11, 28.75, 31.36, 27.03, 32.27, 28.29, 32.55, 26.4 ,
       28.74, 27.79, 32.06, 28.7 , 30.23, 30.1 , 29.89, 27.95, 27.64,
       30.99, 28.66, 28.46, 31.19, 29.54, 26.94, 30.61, 27.06, 29.17,
       30.12, 26.21, 27.15, 29.46, 26.12, 30.86, 35.85, 30.52, 25.5 ,
       27.62, 24.34, 32.1 , 31.26, 30.59, 29.44, 30.08, 30.41, 28.81,
       29.95, 31.15, 31.87, 32.41, 28.35, 30.92, 30.45, 31.64, 28.47,
       32.97, 31.75, 31.38, 28.9 , 30.66, 30.5 , 26.86, 28.05, 32.28,
       33.3 , 34.33, 32.46, 31.86, 28.53, 32.13, 28.78, 29.36, 28.31,
       24.55, 30.03, 30.53, 30.26, 30.11, 31.12, 30.9 , 30.94, 27.24,
       30.91, 30.3 , 27.82, 29.65, 26.43, 30.04, 25.92, 29.35, 29.63,
       24.32, 27.75, 28.39, 31.57, 29.89, 29.58, 31.25, 29.56, 27.31,
       29.81, 28.88, 30.82, 30.19, 26.89, 25.61, 31.04, 27.59, 30.98,
       29.76, 28.96, 27.92, 30.75, 27.96, 28.28, 30.8 , 33.36, 33.29,
       30.03, 30.29, 30.55, 30.22, 27.71, 33.01, 30.28, 29.93, 29.73,
       25.44, 29.25, 29.18, 30.52, 27.73, 30.75, 27.42, 29.01, 31.82,
       28.84, 27.06, 30.91, 28.35, 31.09, 31.07, 31.61, 29.76, 28.94,
       29.  , 30.9 , 31.24, 28.68, 31.74, 31.12, 29.97, 22.89, 28.64,
       31.57, 27.41, 24.72, 30.53, 30.67, 29.29, 32.28, 30.92, 28.55,
       30.7 , 31.87, 29.16, 33.08, 30.06, 28.68, 30.67, 29.91, 28.  ,
       27.1 , 28.86, 32.07, 24.44, 30.76, 29.92, 34.8 , 30.46, 29.08,
       32.97, 31.49, 30.78, 28.93, 30.95, 27.66, 26.5 , 30.79, 29.67,
       28.19, 29.05, 27.33, 30.78, 31.51, 28.79, 27.77, 31.7 , 30.88,
       29.59, 31.4 ])

In [68]:
print("Model Score:", r2_score(y_test,pred))

Model Score: -0.10864567053612673

In [70]:
mape = np.mean(np.abs((y_test - pred)/y_test)) * 100
accuracy = 100 - mape
print(f"Accuracy: {accuracy:.2f}%")

Accuracy: 74.12%

In [71]:
import pickle

In [77]:
import pickle
import os

# Create folder if it doesn't exist
os.makedirs("model", exist_ok=True)

# Save the model
pickle.dump(model, open("model/sales_model.pkl", "wb"))

print("Model saved successfully ✅")

Model saved successfully ✅